[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bdgd-tools"
version = "0.1.0"
description = "Tools for parsing ANEEL BDGD geodatabases and interfacing with OpenDSS"
requires-python = ">=3.10"
dependencies = [
    "geopandas",
    "pyogrio",
    "pydantic"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov"
]